## DataFrame 구조
### - index(row), column(column), data

In [1]:
import pandas as pd

In [2]:
num_list=range(0,51,10)

In [3]:
df_numlist = pd.DataFrame(data=num_list)

In [4]:
df_numlist

0
0   0
1  10
2  20
3  30
4  40
5  50

## Series 구조
### - index(row), data

In [5]:
import pandas as pd
import numpy as np

In [6]:
single_data = np.arange(0.1, 0.6, 0.1)
single_data

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [7]:
series_floats = pd.Series(data=single_data)

In [8]:
series_floats

0    0.1
1    0.2
2    0.3
3    0.4
4    0.5
dtype: float64

In [9]:
type(series_floats)

pandas.core.series.Series

## numpy를 이용해 random한 Dataframe 데이터 생성

In [10]:
import pandas as pd
import numpy as np

In [11]:
pd.__version__

'1.5.3'

In [12]:
np.__version__

'1.24.3'

In [13]:
np.random.randint(0,100) # 0에서 99까지의 숫자 중 랜덤하게 하나의 정수 값을 출력

12

In [14]:
np.random.randint(0,100,size=(10, 5)) # size 옵션 : 10행 5열의 랜덤한 array 행렬

array([[ 1, 66, 97, 36, 94],
       [90,  5,  4, 56, 55],
       [52, 74,  6, 96, 45],
       [60, 23, 96, 42, 70],
       [67,  5, 58, 23, 18],
       [61,  8, 31, 24, 53],
       [29, 40, 53, 77, 74],
       [16, 13, 86, 24, 63],
       [63, 92, 14, 16, 54],
       [96, 30, 79, 62, 15]])

In [15]:
num_array = np.random.randint(0,100,size=(10, 5))

In [16]:
df_by_randint = pd.DataFrame(num_array)
df_by_randint

0   1   2   3   4
0  54   7  96  73  41
1  60  99  21  54  13
2  53  89  34  14  39
3  35  49  23  34  58
4  56  31  81  91  39
5  79   0  79   2  66
6  74  67  27  21  68
7  66   1   3  94  35
8  20  43  25  12  28
9  85  53  28   5  13

## 파이썬 내장 random 모듈 이용해 random한 Dataframe 데이터 생성

In [17]:
import random

In [18]:
random.randrange(0, 100)

14

In [19]:
random_double_list = [[random.randrange(0, 100) for _ in range(5)] for _ in range(5)] # 이중 for문 이용해 array 행렬 작성

In [20]:
random_double_list

[[89, 37, 54, 11, 56],
 [87, 10, 67, 47, 25],
 [55, 58, 60, 43, 5],
 [17, 29, 88, 21, 31],
 [68, 95, 89, 38, 19]]

In [21]:
df_by_randrange = pd.DataFrame(random_double_list)

In [22]:
df_by_randrange

0   1   2   3   4
0  89  37  54  11  56
1  87  10  67  47  25
2  55  58  60  43   5
3  17  29  88  21  31
4  68  95  89  38  19

## 수업

In [23]:
double_list = [
    [1000, '과자','2019-12-31','반품'],
    [2000, '음료', '2020-03-02', '정상'],
    [3000, '아이스크림', '2020-02-03','정상'],
    [1000,'과자','2019-12-31','반품'],
    [2000,'과자','2020-02-03','반품']
    ]
df_sales = pd.DataFrame(data=double_list)
df_sales

0      1           2   3
0  1000     과자  2019-12-31  반품
1  2000     음료  2020-03-02  정상
2  3000  아이스크림  2020-02-03  정상
3  1000     과자  2019-12-31  반품
4  2000     과자  2020-02-03  반품

In [24]:
df_sales = pd.DataFrame(data=double_list, columns=['가격','종류','판매일자','반품여부'])
df_sales

가격     종류        판매일자 반품여부
0  1000     과자  2019-12-31   반품
1  2000     음료  2020-03-02   정상
2  3000  아이스크림  2020-02-03   정상
3  1000     과자  2019-12-31   반품
4  2000     과자  2020-02-03   반품

In [25]:
# dropped_df_sales=df_sales.drop('종류', '판매일자')
# dropped_df_sales

In [26]:
## 필터
condition = (df_sales['반품여부']=='정상')
condition

0    False
1     True
2     True
3    False
4    False
Name: 반품여부, dtype: bool

In [27]:
type(condition)

pandas.core.series.Series

In [28]:
df_sales.loc[condition]

가격     종류        판매일자 반품여부
1  2000     음료  2020-03-02   정상
2  3000  아이스크림  2020-02-03   정상

In [29]:
## 필터 조건 여러개
## and & , or |
condition_or = (df_sales['가격']>=2500) | (df_sales['가격']<=1500)
condition_or

0     True
1    False
2     True
3     True
4    False
Name: 가격, dtype: bool

In [30]:
condition_and = (df_sales['반품여부']=='정상')  | (df_sales['종류']=='과자') & (df_sales['가격']>=1500)
condition_and

0    False
1     True
2     True
3    False
4     True
dtype: bool

In [31]:
df_sales

가격     종류        판매일자 반품여부
0  1000     과자  2019-12-31   반품
1  2000     음료  2020-03-02   정상
2  3000  아이스크림  2020-02-03   정상
3  1000     과자  2019-12-31   반품
4  2000     과자  2020-02-03   반품

In [32]:
# drd_df_sales=df_sales[['가격','반품여부']]
# drd_df_sales

In [33]:
## 요약
df_sales.pivot_table(index='종류', values='가격')

가격
판매일자            
2019-12-31  1000
2020-02-03  2500
2020-03-02  2000

In [56]:
pd.pivot_table(data=df_sales, index='종류', values='가격')

가격
판매일자            
2019-12-31  1000
2020-02-03  2500
2020-03-02  2000

In [57]:
import numpy as np

In [60]:
df_sales.pivot_table(index='종류', values='가격', aggfunc=np.max)

가격
종류         
과자     2000
아이스크림  3000
음료     2000

# 통계 수치 표현


In [35]:
import numpy as np

In [50]:
arr = np.array([6,4,1,3,5,3,10,7,9])

In [51]:
arr

array([ 6,  4,  1,  3,  5,  3, 10,  7,  9])

In [52]:
#평균값
np.mean(arr)

5.333333333333333

In [53]:
#중앙값
np.median(arr)

5.0

In [54]:
#최소값, 최대값
print(np.min(arr),np.max(arr))

1 10


In [55]:
#분산, 표준편차
np.var(arr), np.std(arr)

(7.777777777777778, 2.788866755113585)

In [62]:
df_sales.pivot_table(index=['반품여부', '종류'], values='가격', aggfunc=[np.sum, np.min, np.size])

sum  amin size
              가격    가격   가격
반품여부 종류                    
반품   과자     4000  1000    3
정상   아이스크림  3000  3000    1
     음료     2000  2000    1