## DataFrame 구조
### - index(row), column(column), data

In [1]:
import pandas as pd

In [2]:
num_list=range(0,51,10)

In [3]:
df_numlist = pd.DataFrame(data=num_list)

In [4]:
df_numlist

0
0   0
1  10
2  20
3  30
4  40
5  50

## Series 구조
### - index(row), data

In [5]:
import pandas as pd
import numpy as np

In [6]:
single_data = np.arange(0.1, 0.6, 0.1)
single_data

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [7]:
series_floats = pd.Series(data=single_data)

In [8]:
series_floats

0    0.1
1    0.2
2    0.3
3    0.4
4    0.5
dtype: float64

In [9]:
type(series_floats)

pandas.core.series.Series

## numpy를 이용해 random한 Dataframe 데이터 생성

In [10]:
import pandas as pd
import numpy as np

In [11]:
pd.__version__

'1.5.3'

In [12]:
np.__version__

'1.24.3'

In [13]:
np.random.randint(0,100) # 0에서 99까지의 숫자 중 랜덤하게 하나의 정수 값을 출력

86

In [14]:
np.random.randint(0,100,size=(10, 5)) # size 옵션 : 10행 5열의 랜덤한 array 행렬

array([[36, 72, 71, 29, 83],
       [82, 53, 90, 58, 40],
       [90,  5, 88, 21, 40],
       [15, 33, 24, 24, 65],
       [67, 96, 80, 69, 65],
       [45, 15, 96, 65, 40],
       [54,  8, 26, 22, 32],
       [61,  0, 86, 65, 87],
       [20, 57, 21, 91,  9],
       [30, 10, 52, 95, 93]])

In [15]:
num_array = np.random.randint(0,100,size=(10, 5))

In [16]:
df_by_randint = pd.DataFrame(num_array)
df_by_randint

0   1   2   3   4
0  93  65   8  68  52
1  65   6  72   2  60
2  31  22  28  90  51
3   6  47  89  44  91
4  66  73  51  20  37
5  72  50  78  57  75
6  38  78  12   4   1
7  95  37  25  45  61
8  99  54  20  37  47
9  71  38  56  39   0

## 파이썬 내장 random 모듈 이용해 random한 Dataframe 데이터 생성

In [17]:
import random

In [18]:
random.randrange(0, 100)

93

In [19]:
random_double_list = [[random.randrange(0, 100) for _ in range(5)] for _ in range(5)] # 이중 for문 이용해 array 행렬 작성

In [20]:
random_double_list

[[23, 54, 51, 41, 89],
 [66, 79, 82, 60, 90],
 [6, 56, 0, 84, 20],
 [35, 84, 64, 44, 88],
 [31, 51, 88, 64, 84]]

In [21]:
df_by_randrange = pd.DataFrame(random_double_list)

In [22]:
df_by_randrange

0   1   2   3   4
0  23  54  51  41  89
1  66  79  82  60  90
2   6  56   0  84  20
3  35  84  64  44  88
4  31  51  88  64  84

## 수업

In [23]:
double_list = [
    [1000, '과자','2019-12-31','반품'],
    [2000, '음료', '2020-03-02', '정상'],
    [3000, '아이스크림', '2020-02-03','정상'],
    [1000,'과자','2019-12-31','반품']
    ]
df_double_list = pd.DataFrame(data=double_list)
df_double_list

0      1           2   3
0  1000     과자  2019-12-31  반품
1  2000     음료  2020-03-02  정상
2  3000  아이스크림  2020-02-03  정상
3  1000     과자  2019-12-31  반품

In [24]:
df_sales = pd.DataFrame(data=double_list, columns=['가격','종류','판매일자','반품여부'])
df_sales

가격     종류        판매일자 반품여부
0  1000     과자  2019-12-31   반품
1  2000     음료  2020-03-02   정상
2  3000  아이스크림  2020-02-03   정상
3  1000     과자  2019-12-31   반품

### Drop


In [25]:
type(df_sales)

pandas.core.frame.DataFrame

In [26]:
col_sales=df_sales.columns
col_sales

Index(['가격', '종류', '판매일자', '반품여부'], dtype='object')

In [27]:
col_sales=col_sales.to_list()

In [28]:
idx_sales=df_sales.index
idx_sales

RangeIndex(start=0, stop=4, step=1)

In [29]:
df_sales.values

array([[1000, '과자', '2019-12-31', '반품'],
       [2000, '음료', '2020-03-02', '정상'],
       [3000, '아이스크림', '2020-02-03', '정상'],
       [1000, '과자', '2019-12-31', '반품']], dtype=object)

In [30]:
df_sales.drop(columns=[col_sales[0],col_sales[3]])

종류        판매일자
0     과자  2019-12-31
1     음료  2020-03-02
2  아이스크림  2020-02-03
3     과자  2019-12-31

In [31]:
df_sales

가격     종류        판매일자 반품여부
0  1000     과자  2019-12-31   반품
1  2000     음료  2020-03-02   정상
2  3000  아이스크림  2020-02-03   정상
3  1000     과자  2019-12-31   반품

### inplace=True

In [32]:
# df_sales.drop(columns=['종류', '판매일자', ], inplace=True) 
# inplace는 왠만해서는 사용하지 않기

In [34]:
df_sales_dropped = df_sales.drop(columns=['종류', '판매일자', ])
df_sales_dropped

가격 반품여부
0  1000   반품
1  2000   정상
2  3000   정상
3  1000   반품